remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: true
titles_from_headings:
  enabled: true

# Modify the contents below for the specific project.
title: "WeThePeople"
description: "Centralize Laws and Notification of New bills"
author: "Dagoberto Garcia"
name: "Dagoberto Garcia"
# Do not change the following line.
  copyright: true
