remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: true

# Modify the contents below for the specific project.

title: "WeThePeople"

description: "Centralize Laws and Notification of New bills"

author:

  name: "Dagoberto"

# Do not change the following line.
  copyright: true

theme:
theme: jekyll-theme-midnight