remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "We The People"
description: "Centralize Laws and Notification of New bills"
author: "wyldus"
  name: "Dagoberto Garcia"

# Do not change the following line.
  copyright: true
